In [37]:
#cau3
import numpy as np
print(np.__version__)

1.26.4


In [13]:
#Cau4
np.empty(10)

array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [36]:
#Cau5
arr = np.array([26, 7, 19, 27, 12, 29])

print(arr)

[26  7 19 27 12 29]


In [30]:
#Cau5,6
arr = np.random.randint(1, 9, size = 10)
arr1 = np.random.random(10)
print(arr1)
print(arr)

print("gia tri pt5: ", arr[5])

print("so chieu: ", np.ndim(arr))
print("so phan tu: ", np.size(arr))

[0.99062542 0.32128813 0.23820145 0.70873749 0.18399348 0.13102284
 0.47362893 0.81448727 0.98112993 0.39264442]
[4 6 6 7 4 8 4 5 7 7]
gia tri pt5:  8
so chieu:  1
so phan tu:  10


In [35]:
#Cau7
arr = np.random.random((3, 4))

print(arr)

[[0.18788718 0.32103289 0.28211549 0.48103197]
 [0.02155364 0.22198745 0.20314905 0.2027216 ]
 [0.55508541 0.67002835 0.68350576 0.13787423]]


In [57]:
#Cau8
arr = np.array([[5,10,21], [11,23,18], [22,19,35], [96,22,26]])
print(arr)
print("so chieu: ", np.ndim(arr))
print("so dong, cot:", np.shape(arr))

arr2 = np.copy(arr)
arr2 = arr[1:4, 1:3]
print(arr2)

arr[3,1] = 30
print('\nsau khi thay doi:\n', arr)

[[ 5 10 21]
 [11 23 18]
 [22 19 35]
 [96 22 26]]
so chieu:  2
so dong, cot: (4, 3)
[[23 18]
 [19 35]
 [22 26]]

sau khi thay doi:
 [[ 5 10 21]
 [11 23 18]
 [22 19 35]
 [96 30 26]]


In [65]:
#Cau9
arr = np.random.randint(10, 20, size = 10)
print(arr)

arr2 = arr.reshape(2,5)
print(arr2, "\nso chieu: ", np.ndim(arr2))

[11 17 11 15 17 16 14 10 13 10]
[[11 17 11 15 17]
 [16 14 10 13 10]] 
so chieu:  2


In [70]:
#Cau10
arr = np.array([99, 46, 87, 62, 11, 32])
print("max: ", np.max(arr), "min: ", np.min(arr))
print("\nsort:\n", np.sort(arr))

count = 0
if arr[4] % 2 == 0:
    print("Phan tu thu 4 la so chan")
else:
    print("Phan tu thu 4 la so le")

for i in arr:
    if i % 2 == 0:
        count += 1

print("mean: ", np.mean(arr))
print("median", np.median(arr))
print("sum: ", np.sum(arr))

arr[arr == 87] = np.mean(arr)
print("Mang sau khi thay mean: ", arr)

np.delete(arr, )

arr2 = arr[arr != 62]
print("Mang sau khi xoa 62: ", arr2)

max:  99 min:  11

sort:
 [11 32 46 62 87 99]
Phan tu thu 4 la so le
mean:  56.166666666666664
median 54.0
sum:  337
Mang sau khi thay mean:  [99 46 56 62 11 32]
Mang sau khi xoa 62:  [99 46 56 11 32]


In [106]:
#Cau11
arr1 = np.array([[5, 10, 21],
                 [11, 23, 18],
                 [22, 19, 35]])

arr2 = np.array([[50, 10, 41],
                 [61, 23, 28],
                 [42, 11, 25]])

arr3 = np.array([[96, 22, 26],
                 [87, 56, 23],
                 [90, 75, 32]])

print(arr1[1:3, 0:3])

mean_arr2 = np.mean(arr2)
print(mean_arr2)
arr1[:, 0] = mean_arr2
print("Thay doi mean: ", arr1)

print("tong value arr3: ", np.sum(arr3))

arr3[-1, :] = -1
print('\n', arr3)

new_arr = np.copy(arr2)
print("chieu ma tran moi: ", np.ndim(new_arr))

new_arr = np.ravel(new_arr)
print("new arr sau khi dua ve vector:\n", new_arr)
new_arr1 = np.append(new_arr, 45)
print("new arr sau khi them cuoi: ", new_arr1)

new_arr2 = np.insert(new_arr1, 0, 99)
print("new arr sau khi them dau: ", new_arr2)


matrix_3d = np.stack([arr1, arr2, arr3], axis=0)
print(list_matrix)
list_matrix = np.ndarray.tolist(matrix_3d)

print('\n',list_matrix)

[[11 23 18]
 [22 19 35]]
32.333333333333336
Thay doi mean:  [[32 10 21]
 [32 23 18]
 [32 19 35]]
tong value arr3:  507

 [[96 22 26]
 [87 56 23]
 [-1 -1 -1]]
chieu ma tran moi:  2
new arr sau khi dua ve vector:
 [50 10 41 61 23 28 42 11 25]
new arr sau khi them cuoi:  [50 10 41 61 23 28 42 11 25 45]
new arr sau khi them dau:  [99 50 10 41 61 23 28 42 11 25 45]
[[[32, 10, 21], [32, 23, 18], [32, 19, 35]], [[50, 10, 41], [61, 23, 28], [42, 11, 25]], [[96, 22, 26], [87, 56, 23], [-1, -1, -1]]]

 [[[32, 10, 21], [32, 23, 18], [32, 19, 35]], [[50, 10, 41], [61, 23, 28], [42, 11, 25]], [[96, 22, 26], [87, 56, 23], [-1, -1, -1]]]


In [113]:
#cau12
ds = [15, 32, 10, 32, 29, 48, 21]
arr = np.asarray(ds)

print(arr)

print(np.size(arr), np.ndim(arr))

#arr1 = arr.reshape(2,4)
print(arr)

arr1 = np.insert(arr, 2, 55)
print(arr1.reshape(4,2))

print("print phan tu vi tri le: \n",arr1[np.where(arr1 % 2 != 0)])

[15 32 10 32 29 48 21]
7 1
[15 32 10 32 29 48 21]
[[15 32]
 [55 10]
 [32 29]
 [48 21]]
print phan tu vi tri le: 
 [15 55 29 21]


In [138]:
#Cau13
arr = np.loadtxt("C:/Users/huynh/Documents/jupyter Running/Data Analysis/Data/sinhvien.txt", dtype='str')
print(arr)

new_row = np.array(['Stt', 'HoTen', 'Tuoi'])
arr_new = np.vstack([new_row, arr])
#arr_new = np.insert(arr, 0, new_row)

print('\n', arr_new)

#bat buoc file ghi ra voi dinh dang string
np.savetxt("C:/Users/huynh/Documents/jupyter Running/Data Analysis/Data/sinhviensave.txt", arr_new, delimiter=' ', fmt='%s') 

arr_age = arr[0:5 , -1]

print(arr_age)

arr_age = np.mean(arr_age, dtype=float)
print(arr_age)

[['1' 'Thanh' '20']
 ['2' 'Tam' '21']
 ['3' 'Binh' '22']
 ['4' 'Chinh' '23']
 ['5' 'Lan' '21']]

 [['Stt' 'HoTen' 'Tuoi']
 ['1' 'Thanh' '20']
 ['2' 'Tam' '21']
 ['3' 'Binh' '22']
 ['4' 'Chinh' '23']
 ['5' 'Lan' '21']]
['20' '21' '22' '23' '21']
21.4
